"""Asset configurations for Crazyflie project."""

from .alphabot import ALPHABOT_CFG, ALPHABOT_USD_PATH, ALPHABOT_JOINTS_NAMES, \
    ACTUATORS_LEFT_WHEEL, \
    ACTUATORS_RIGHT_WHEEL
    
from .jackal import (
    JACKAL_CFG,
    JACKAL_JOINTS_NAMES,
    JACKAL_ACTUATORS_LEFT_WHEEL,
    JACKAL_ACTUATORS_RIGHT_WHEEL,
)

__all__ = ["JACKAL_CFG","JACKAL_JOINTS_NAMES","JACKAL_ACTUATORS_LEFT_WHEEL","JACKAL_ACTUATORS_RIGHT_WHEEL"]
