[project]
name = "isaaclab_models"
version = "0.1.0"
description = "Model training using NVIDIA Isaac Sim"
requires-python = "~=3.11.0"
dependencies = [
    "isaacsim[all,extscache]==5.1.0",
    "torch==2.7.0",
    "torchvision==0.22.0",
]

[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
isaacsim = { index = "nvidia" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
